/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Enable AVR Serial0 handling */
#define AVR_ENABLE_SERIAL0

/* Enable AVR Serial1 handling */
#undef AVR_ENABLE_SERIAL1

/* Enable AVR Serial2 handling */
#undef AVR_ENABLE_SERIAL2

/* Enable AVR Serial3 handling */
#undef AVR_ENABLE_SERIAL3

/* The buffer size used for UART reception */
#define SMP_SERIAL_DEVICE_RX_BUFFER_SIZE 256

#define SMP_SIZE_T_SIZE 4

