/*
 * Autogenerated by the Meson build system.
 * Do not edit, your changes will be lost.
 */

#pragma once

/* Enable AVR Serial0 handling */
#define AVR_ENABLE_SERIAL0

/* Enable AVR Serial1 handling */
#undef AVR_ENABLE_SERIAL1

/* Enable AVR Serial2 handling */
#undef AVR_ENABLE_SERIAL2

/* Enable AVR Serial3 handling */
#undef AVR_ENABLE_SERIAL3

/* Number of bytes processed by a single call of smp_context_process_fd */
#define SMP_CONTEXT_PROCESS_CHUNK_SIZE 1

/* The buffer size used for UART reception on AVR */
#define SMP_SERIAL_DEVICE_AVR_CBUF_SIZE 64

#define SMP_SIZE_T_SIZE 4

